[tool.poetry]
name = "grk"
version = "0.1.0"
description = "CLI tool to push cfold to Grok LLM and save output"
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"


[tool.poetry.dependencies]
python = ">=3.10,<3.14"
click = "^8.1.7"
requests = "^2.32.3"
pyyaml = "^6.0.2"

[tool.poetry.scripts]
grk = "grk.cli:main"

[tool.poetry.group.dev.dependencies]
pyinstaller = "^6.13.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
