[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "grk"
version = "0.2.6"
description = "CLI tool for Grok LLM"
authors = [{ name = "wr1", email = "8971152+wr1@users.noreply.github.com"}]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "xai-sdk",
    "pydantic",
    "rich",
    "ruamel.yaml",
    "treeparse",
    "pytest",
    "pytest-mock",
    "pytest-cov",
    "opentelemetry-sdk>=1.15.0,<1.20.0",
    "numpy",
]

[project.scripts]
grk = "grk.cli.cli:main"

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "W"]
ignore = []

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--cov=src --cov-report=term-missing"
